#
# Application name 
#

NAME=hierordering



#
# Source files
#

CCSRCS=$(NAME).cpp

#
# Libraries
#

PKG_LIBS=-lNeuron -lRNDataStructures -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lpng -ljpeg -lfglut


#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















