#
# Application name 
#

NAME=entropy



#
# Source files
#

CCSRCS=$(NAME).cpp

#
# Libraries
#

PKG_LIBS=-lRNML -lNeuron -lRNDataStructures -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lpng -ljpeg `pkg-config --libs opencv`


#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















