#
# Package name and list of source files.
#

NAME=Neuron
CCSRCS= $(NAME).cpp \
	NeuronVolume.cpp \
	NeuronReconstruction.cpp \
	NeuronHumanLabel.cpp \
	NeuronPrediction.cpp \
	NeuronSupervoxel.cpp \
	NeuronCellular.cpp \
	NeuronExtracellular.cpp \
	NeuronPredictionBoundary.cpp \
	NeuronBoundary.cpp \
	NeuronData.cpp \
	NeuronVoxel.cpp

#
# RING library makefile
#

include ../../makefiles/Makefile.pkgs







