#
# Application name 
#

NAME=dijkstra



#
# Source files
#

CCSRCS=$(NAME).cpp

#
# Libraries
#

#PKG_LIBS=-lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lNeuron

PKG_LIBS=-lNeuron -lRNDataStructures -lR3Graphics -lR3Shapes -lR2Shapes -lRNMath -lRNBasics -lpng -ljpeg


#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















