#
# Application name 
#

NAME=metamerge



#
# Source files
#

CCSRCS=$(NAME).cpp

#
# Libraries
#

PKG_LIBS=-lRNDataStructures -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lpng -ljpeg


#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















