#
# Package name and list of source files.
#

NAME=RNML
CCSRCS= $(NAME).cpp \
	RNClassifier.cpp \
	RNDataset.cpp \
	RNRandomForest.cpp

#
# RING library makefile
#

include ../../makefiles/Makefile.pkgs







