#
# Application name 
#

NAME=neurondata



#
# Source files
#

CCSRCS=$(NAME).cpp

#
# Libraries
#

PKG_LIBS=-lNeuron -lRNML -lRNDataStructures -lR3Graphics -lR3Shapes -lR2Shapes -lRNBasics -lpng -ljpeg -lfglut `pkg-config --libs opencv`


#
# Include standard makefile
#

include ../../makefiles/Makefile.apps















