#
# Package name and list of source files.
#

NAME=RNDataStructures
CCSRCS=$(NAME).cpp \
	RNMinBinaryHeap.cpp \
	RNVector.cpp \
	RNMetaRawFile.cpp \
	RNHistogram.cpp \
	RNMisc.cpp \
	RNDistribution.cpp \
	RNSkeleton.cpp \
	RNPyPlot.cpp



#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs



