#
# Package name and list of source files.
#

NAME=gco
CCSRCS= GCoptimization.cpp \
  maxflow.cpp \
  graph.cpp \
  LinkedBlockList.cpp 



#
# R3 library makefile
#

include ../../makefiles/Makefile.pkgs



